spring:
 datasource:
   validationQuery: SELECT 1 FROM DUAL
   url: jdbc:oracle:thin:@130.85.51.9:1521:newfx
 #  url: jdbc:oracle:thin:@10.81.93.47:1521:boncdb
   driverClassName: oracle.jdbc.OracleDriver
   username: yyt
   password: bonc#2016
   type: com.alibaba.druid.pool.DruidDataSource
   platform: oracle
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  #初始化数量
   initialSize: 1
   #最小活跃数
   minIdle: 3
  #最大活跃数
   maxActive: 20
  # 配置获取连接等待超时的时间
   maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
   timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
   minEvictableIdleTimeMillis: 30000
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
   poolPreparedStatements: false
   maxPoolPreparedStatementPerConnectionSize: 20
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
   useGlobalDataSourceStat: true
   maxOpenPreparedStatements: 20

mybatis:
#写com.bonc.mapper 或com/bonc/mapper会报错
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bonc.pojo
